#!/usr/bin/env python3
"""Stand-in for launchctl in the tests: `list` prints the services from $FAKE_PLAN ("services")."""
import json
import os
import sys

plan = json.load(open(os.environ["FAKE_PLAN"]))
with open(os.environ["FAKE_CALLS"], "a") as calls:
    calls.write(json.dumps(["launchctl"] + sys.argv[1:]) + "\n")
if sys.argv[1:] == ["list"]:
    print("PID\tStatus\tLabel")
    for pid, label in plan.get("services", []):
        print("%s\t0\t%s" % (pid, label))
