#!/usr/bin/env python3
"""Stand-in for ps in the tests: start time of a process from $FAKE_PLAN ("started")."""
import json
import os
import sys

plan = json.load(open(os.environ["FAKE_PLAN"]))
print(plan.get("started", {}).get(sys.argv[-1], "Mon Jan  5 08:00:00 2026"))
