"""Report texts in English, German, French, Italian and Spanish.

Every language has every key with the same placeholders ({0}, {1}); tests/test_texts.py checks it.

Copyright (c) 2026 Simon Eckmiller. MIT License.
"""
from __future__ import annotations

TEXTS = {
    "en": {
        "title": "Upgrade All report", "tagline": "Simon says: upgrade all!",
        "hero_ok": "Your Mac is up to date.", "hero_fixed": "Your Mac is up to date. Errors were fixed automatically.",
        "hero_failed": "Updated with errors. Please check the report.", "hero_hooks": "Your Mac is up to date. An extra step had a problem.",
        "status_ok": "All update steps succeeded.", "status_fixed": "Failed at first, fixed by the automatic retry: {0}.",
        "status_failed": "Still failed after the automatic retry: {0}.", "status_aborted": "topgrade ended with an error but printed no summary; the run probably stopped early.",
        "status_timeout": "topgrade did not finish within {0} minutes and was stopped.",
        "status_hooks": "Extra steps with problems: {0}.",
        "run": "Run", "duration": "Duration", "host": "Mac", "next_run": "Next automatic run", "every_days": "every {0} days",
        "topgrade": "topgrade", "log_file": "Log file",
        "section_status": "Status", "section_steps": "Update steps", "section_fixes": "Self-correction",
        "section_hooks": "Extra steps", "section_log": "Full log",
        "col_step": "Step", "col_result": "Result", "col_retry": "Retry",
        "retry_result": "retry: {0}", "not_retried": "not retried (unknown step)", "no_retry_needed": "–",
        "no_summary": "No summary found in the log.",
        "fix_pre_updated": "topgrade was updated first: {0} → {1}, so the run cannot remove its own running version.",
        "fix_pre_current": "topgrade was already up to date ({0}).", "fix_pre_failed": "Updating topgrade first failed (exit {0}); the run used {1}.",
        "fix_pre_off": "Updating topgrade first is turned off.",
        "fix_retry": "Retried: {0}. Fixed: {1}. Still failing: {2}.", "fix_no_retry": "No retry needed.",
        "fix_unknown": "Failed steps without a known id were not retried: {0}.",
        "fix_services": "Restarted because they still ran the removed old version: {0}.",
        "fix_services_failed": "Restart failed: {0}. See the log.",
        "hook_ok": "OK", "hook_skipped": "skipped", "hook_failed": "failed (exit {0})",
        "access_title": "macOS denied access, also on the retry.",
        "access_text": "A step could not reach a protected place (for example an external disk). macOS stores this permission per program version: {0}. Run this once and click Allow when macOS asks:",
        "show_log": "Show log ({0})", "show_retry_log": "Show retry log ({0})", "show_hook_log": "Show output",
        "footer": "Created by Upgrade All {0} · runs in the background as a LaunchAgent", "back_to_top": "Back to top",
        "pill_ok": "OK", "pill_fixed": "OK (fixed)", "pill_warn": "CHECK",
        "outcome_ok": "OK", "outcome_failed": "FAILED", "outcome_skipped": "SKIPPED",
    },
    "de": {
        "title": "Upgrade-All-Bericht", "tagline": "Simon says: upgrade all!",
        "hero_ok": "Dein Mac ist auf dem neuesten Stand.", "hero_fixed": "Dein Mac ist auf dem neuesten Stand. Fehler wurden automatisch behoben.",
        "hero_failed": "Aktualisiert mit Fehlern. Bitte den Bericht prüfen.", "hero_hooks": "Dein Mac ist auf dem neuesten Stand. Ein Zusatzschritt hatte ein Problem.",
        "status_ok": "Alle Update-Schritte waren erfolgreich.", "status_fixed": "Zuerst fehlgeschlagen, durch die automatische Wiederholung behoben: {0}.",
        "status_failed": "Auch nach der automatischen Wiederholung fehlgeschlagen: {0}.", "status_aborted": "topgrade endete mit Fehler, aber ohne Zusammenfassung; der Lauf wurde vermutlich vorzeitig abgebrochen.",
        "status_timeout": "topgrade war nach {0} Minuten nicht fertig und wurde beendet.",
        "status_hooks": "Zusatzschritte mit Problemen: {0}.",
        "run": "Lauf", "duration": "Dauer", "host": "Mac", "next_run": "Nächster automatischer Lauf", "every_days": "alle {0} Tage",
        "topgrade": "topgrade", "log_file": "Log-Datei",
        "section_status": "Status", "section_steps": "Update-Schritte", "section_fixes": "Selbstkorrektur",
        "section_hooks": "Zusatzschritte", "section_log": "Vollständiges Log",
        "col_step": "Schritt", "col_result": "Ergebnis", "col_retry": "Wiederholung",
        "retry_result": "Wiederholung: {0}", "not_retried": "nicht wiederholt (unbekannter Schritt)", "no_retry_needed": "–",
        "no_summary": "Keine Zusammenfassung im Log gefunden.",
        "fix_pre_updated": "topgrade wurde vorab erneuert: {0} → {1}, damit der Lauf seine laufende Version nicht selbst entfernt.",
        "fix_pre_current": "topgrade war aktuell ({0}).", "fix_pre_failed": "Das vorherige Erneuern von topgrade schlug fehl (Exit {0}); der Lauf nutzte {1}.",
        "fix_pre_off": "Das vorherige Erneuern von topgrade ist ausgeschaltet.",
        "fix_retry": "Wiederholt: {0}. Behoben: {1}. Weiter fehlerhaft: {2}.", "fix_no_retry": "Keine Wiederholung nötig.",
        "fix_unknown": "Fehlgeschlagene Schritte ohne bekannte Kennung wurden nicht wiederholt: {0}.",
        "fix_services": "Neu gestartet, weil sie noch die entfernte alte Version ausführten: {0}.",
        "fix_services_failed": "Neustart fehlgeschlagen: {0}. Siehe Log.",
        "hook_ok": "OK", "hook_skipped": "übersprungen", "hook_failed": "fehlgeschlagen (Exit {0})",
        "access_title": "macOS hat den Zugriff verweigert, auch bei der Wiederholung.",
        "access_text": "Ein Schritt erreichte einen geschützten Ort nicht (zum Beispiel eine externe Festplatte). macOS speichert diese Erlaubnis je Programmversion: {0}. Einmal ausführen und auf Erlauben klicken, wenn macOS fragt:",
        "show_log": "Log anzeigen ({0})", "show_retry_log": "Log der Wiederholung anzeigen ({0})", "show_hook_log": "Ausgabe anzeigen",
        "footer": "Erstellt von Upgrade All {0} · läuft im Hintergrund als LaunchAgent", "back_to_top": "Nach oben",
        "pill_ok": "OK", "pill_fixed": "OK (behoben)", "pill_warn": "PRÜFEN",
        "outcome_ok": "OK", "outcome_failed": "FEHLGESCHLAGEN", "outcome_skipped": "ÜBERSPRUNGEN",
    },
    "fr": {
        "title": "Rapport Upgrade All", "tagline": "Simon says: upgrade all!",
        "hero_ok": "Votre Mac est à jour.", "hero_fixed": "Votre Mac est à jour. Des erreurs ont été corrigées automatiquement.",
        "hero_failed": "Mise à jour avec erreurs. Veuillez consulter le rapport.", "hero_hooks": "Votre Mac est à jour. Une étape supplémentaire a rencontré un problème.",
        "status_ok": "Toutes les étapes de mise à jour ont réussi.", "status_fixed": "D'abord en échec, corrigé par la nouvelle tentative automatique : {0}.",
        "status_failed": "Toujours en échec après la nouvelle tentative automatique : {0}.", "status_aborted": "topgrade s'est terminé avec une erreur mais sans résumé ; l'exécution s'est probablement arrêtée trop tôt.",
        "status_timeout": "topgrade n'avait pas terminé après {0} minutes et a été arrêté.",
        "status_hooks": "Étapes supplémentaires avec problèmes : {0}.",
        "run": "Exécution", "duration": "Durée", "host": "Mac", "next_run": "Prochaine exécution automatique", "every_days": "tous les {0} jours",
        "topgrade": "topgrade", "log_file": "Fichier journal",
        "section_status": "État", "section_steps": "Étapes de mise à jour", "section_fixes": "Autocorrection",
        "section_hooks": "Étapes supplémentaires", "section_log": "Journal complet",
        "col_step": "Étape", "col_result": "Résultat", "col_retry": "Nouvelle tentative",
        "retry_result": "nouvelle tentative : {0}", "not_retried": "pas de nouvelle tentative (étape inconnue)", "no_retry_needed": "–",
        "no_summary": "Aucun résumé trouvé dans le journal.",
        "fix_pre_updated": "topgrade a d'abord été mis à jour : {0} → {1}, pour que l'exécution ne supprime pas sa propre version en cours.",
        "fix_pre_current": "topgrade était déjà à jour ({0}).", "fix_pre_failed": "La mise à jour préalable de topgrade a échoué (code {0}) ; l'exécution a utilisé {1}.",
        "fix_pre_off": "La mise à jour préalable de topgrade est désactivée.",
        "fix_retry": "Nouvelle tentative : {0}. Corrigé : {1}. Toujours en échec : {2}.", "fix_no_retry": "Aucune nouvelle tentative nécessaire.",
        "fix_unknown": "Étapes en échec sans identifiant connu, non retentées : {0}.",
        "fix_services": "Redémarrés car ils exécutaient encore l'ancienne version supprimée : {0}.",
        "fix_services_failed": "Échec du redémarrage : {0}. Voir le journal.",
        "hook_ok": "OK", "hook_skipped": "ignorée", "hook_failed": "en échec (code {0})",
        "access_title": "macOS a refusé l'accès, même lors de la nouvelle tentative.",
        "access_text": "Une étape n'a pas pu atteindre un emplacement protégé (par exemple un disque externe). macOS enregistre cette autorisation par version de programme : {0}. Exécutez ceci une fois et cliquez sur Autoriser quand macOS le demande :",
        "show_log": "Afficher le journal ({0})", "show_retry_log": "Afficher le journal de la nouvelle tentative ({0})", "show_hook_log": "Afficher la sortie",
        "footer": "Créé par Upgrade All {0} · s'exécute en arrière-plan comme LaunchAgent", "back_to_top": "Retour en haut",
        "pill_ok": "OK", "pill_fixed": "OK (corrigé)", "pill_warn": "À VÉRIFIER",
        "outcome_ok": "OK", "outcome_failed": "ÉCHEC", "outcome_skipped": "IGNORÉ",
    },
    "it": {
        "title": "Rapporto Upgrade All", "tagline": "Simon says: upgrade all!",
        "hero_ok": "Il tuo Mac è aggiornato.", "hero_fixed": "Il tuo Mac è aggiornato. Gli errori sono stati corretti automaticamente.",
        "hero_failed": "Aggiornato con errori. Controlla il rapporto.", "hero_hooks": "Il tuo Mac è aggiornato. Un passaggio aggiuntivo ha avuto un problema.",
        "status_ok": "Tutti i passaggi di aggiornamento sono riusciti.", "status_fixed": "Falliti all'inizio, corretti dal nuovo tentativo automatico: {0}.",
        "status_failed": "Ancora falliti dopo il nuovo tentativo automatico: {0}.", "status_aborted": "topgrade è terminato con un errore ma senza riepilogo; probabilmente l'esecuzione si è interrotta prima.",
        "status_timeout": "topgrade non aveva finito dopo {0} minuti ed è stato fermato.",
        "status_hooks": "Passaggi aggiuntivi con problemi: {0}.",
        "run": "Esecuzione", "duration": "Durata", "host": "Mac", "next_run": "Prossima esecuzione automatica", "every_days": "ogni {0} giorni",
        "topgrade": "topgrade", "log_file": "File di log",
        "section_status": "Stato", "section_steps": "Passaggi di aggiornamento", "section_fixes": "Autocorrezione",
        "section_hooks": "Passaggi aggiuntivi", "section_log": "Log completo",
        "col_step": "Passaggio", "col_result": "Risultato", "col_retry": "Nuovo tentativo",
        "retry_result": "nuovo tentativo: {0}", "not_retried": "non ripetuto (passaggio sconosciuto)", "no_retry_needed": "–",
        "no_summary": "Nessun riepilogo trovato nel log.",
        "fix_pre_updated": "topgrade è stato aggiornato prima: {0} → {1}, così l'esecuzione non rimuove la propria versione in uso.",
        "fix_pre_current": "topgrade era già aggiornato ({0}).", "fix_pre_failed": "L'aggiornamento preliminare di topgrade è fallito (codice {0}); l'esecuzione ha usato {1}.",
        "fix_pre_off": "L'aggiornamento preliminare di topgrade è disattivato.",
        "fix_retry": "Ripetuti: {0}. Corretti: {1}. Ancora falliti: {2}.", "fix_no_retry": "Nessun nuovo tentativo necessario.",
        "fix_unknown": "Passaggi falliti senza un identificativo noto, non ripetuti: {0}.",
        "fix_services": "Riavviati perché eseguivano ancora la vecchia versione rimossa: {0}.",
        "fix_services_failed": "Riavvio fallito: {0}. Vedi il log.",
        "hook_ok": "OK", "hook_skipped": "saltato", "hook_failed": "fallito (codice {0})",
        "access_title": "macOS ha negato l'accesso, anche al nuovo tentativo.",
        "access_text": "Un passaggio non ha raggiunto una posizione protetta (ad esempio un disco esterno). macOS salva questa autorizzazione per versione del programma: {0}. Eseguilo una volta e fai clic su Consenti quando macOS lo chiede:",
        "show_log": "Mostra il log ({0})", "show_retry_log": "Mostra il log del nuovo tentativo ({0})", "show_hook_log": "Mostra l'output",
        "footer": "Creato da Upgrade All {0} · gira in background come LaunchAgent", "back_to_top": "Torna su",
        "pill_ok": "OK", "pill_fixed": "OK (corretto)", "pill_warn": "DA CONTROLLARE",
        "outcome_ok": "OK", "outcome_failed": "FALLITO", "outcome_skipped": "SALTATO",
    },
    "es": {
        "title": "Informe de Upgrade All", "tagline": "Simon says: upgrade all!",
        "hero_ok": "Tu Mac está al día.", "hero_fixed": "Tu Mac está al día. Los errores se corrigieron automáticamente.",
        "hero_failed": "Actualizado con errores. Revisa el informe.", "hero_hooks": "Tu Mac está al día. Un paso adicional tuvo un problema.",
        "status_ok": "Todos los pasos de actualización se completaron.", "status_fixed": "Fallaron al principio y el reintento automático los corrigió: {0}.",
        "status_failed": "Siguen fallando tras el reintento automático: {0}.", "status_aborted": "topgrade terminó con un error pero sin resumen; probablemente la ejecución se detuvo antes.",
        "status_timeout": "topgrade no terminó en {0} minutos y se detuvo.",
        "status_hooks": "Pasos adicionales con problemas: {0}.",
        "run": "Ejecución", "duration": "Duración", "host": "Mac", "next_run": "Próxima ejecución automática", "every_days": "cada {0} días",
        "topgrade": "topgrade", "log_file": "Archivo de registro",
        "section_status": "Estado", "section_steps": "Pasos de actualización", "section_fixes": "Autocorrección",
        "section_hooks": "Pasos adicionales", "section_log": "Registro completo",
        "col_step": "Paso", "col_result": "Resultado", "col_retry": "Reintento",
        "retry_result": "reintento: {0}", "not_retried": "sin reintento (paso desconocido)", "no_retry_needed": "–",
        "no_summary": "No se encontró ningún resumen en el registro.",
        "fix_pre_updated": "topgrade se actualizó primero: {0} → {1}, para que la ejecución no elimine su propia versión en uso.",
        "fix_pre_current": "topgrade ya estaba al día ({0}).", "fix_pre_failed": "La actualización previa de topgrade falló (código {0}); la ejecución usó {1}.",
        "fix_pre_off": "La actualización previa de topgrade está desactivada.",
        "fix_retry": "Reintentados: {0}. Corregidos: {1}. Siguen fallando: {2}.", "fix_no_retry": "No hizo falta reintentar.",
        "fix_unknown": "Pasos fallidos sin identificador conocido, no reintentados: {0}.",
        "fix_services": "Reiniciados porque aún ejecutaban la versión antigua eliminada: {0}.",
        "fix_services_failed": "Falló el reinicio: {0}. Ver el registro.",
        "hook_ok": "OK", "hook_skipped": "omitido", "hook_failed": "fallido (código {0})",
        "access_title": "macOS denegó el acceso, también en el reintento.",
        "access_text": "Un paso no pudo llegar a un lugar protegido (por ejemplo un disco externo). macOS guarda este permiso por versión del programa: {0}. Ejecuta esto una vez y haz clic en Permitir cuando macOS lo pregunte:",
        "show_log": "Mostrar registro ({0})", "show_retry_log": "Mostrar registro del reintento ({0})", "show_hook_log": "Mostrar salida",
        "footer": "Creado por Upgrade All {0} · se ejecuta en segundo plano como LaunchAgent", "back_to_top": "Volver arriba",
        "pill_ok": "OK", "pill_fixed": "OK (corregido)", "pill_warn": "REVISAR",
        "outcome_ok": "OK", "outcome_failed": "FALLIDO", "outcome_skipped": "OMITIDO",
    },
}


def text(language: str, key: str, *args) -> str:
    template = TEXTS.get(language, TEXTS["en"]).get(key) or TEXTS["en"][key]
    return template.format(*args)
